# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`


In [3]:
nullv=np.zeros(10)
print(nullv)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`


In [5]:
a1=np.zeros(10)
a1[4]=1
print(a1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [7]:
a2=np.arange(10,50)
print(a2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [9]:
a3=np.reshape(np.arange(0,9),(3,3))
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [12]:
a6=np.nonzero([1,2,0,0,4,0])
print(a6)

(array([0, 1, 4]),)


#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [14]:
a7=np.eye(3,3)
print(a7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [30]:
a8=np.random.random((3,3,3))
print(a8)

[[[0.5906594  0.244188   0.95045519]
  [0.36280949 0.44144373 0.22988594]
  [0.72129669 0.84395579 0.56221253]]

 [[0.3868899  0.62237534 0.21356436]
  [0.45787602 0.69696571 0.02148672]
  [0.22171023 0.03801035 0.13677175]]

 [[0.51642621 0.83341268 0.33406024]
  [0.48916887 0.64706011 0.39237751]
  [0.90823294 0.62375245 0.40581237]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [36]:
a9=np.random.random((10,10))
print(a9)
print('\n')
print(a9.min())
print(a9.max())

[[0.46164766 0.06271809 0.95023124 0.24553862 0.85787606 0.77696121
  0.19998362 0.35369199 0.96552904 0.25620589]
 [0.11365215 0.93079208 0.49938705 0.65560911 0.17249359 0.96423371
  0.55496293 0.62497553 0.84588059 0.42889631]
 [0.04644681 0.0267856  0.73516853 0.69013298 0.25198364 0.04266352
  0.01142972 0.59990448 0.50072096 0.19624444]
 [0.49884695 0.71996235 0.73703304 0.1645668  0.82780743 0.75582188
  0.24652156 0.74902073 0.28236349 0.73181587]
 [0.45628156 0.62989073 0.74575951 0.75878043 0.85397372 0.63675212
  0.50707951 0.19971596 0.26708224 0.56878916]
 [0.05228968 0.44455602 0.23732461 0.24734577 0.87424315 0.84531016
  0.87643144 0.90741605 0.601115   0.56810785]
 [0.07224203 0.26440721 0.76475515 0.22641955 0.06925576 0.90325633
  0.11187606 0.04799825 0.51538289 0.62218284]
 [0.5984476  0.54139099 0.8409227  0.12494084 0.36663671 0.68835732
  0.13935212 0.1151808  0.54290595 0.22477307]
 [0.68802156 0.70830624 0.97439506 0.05635351 0.89587747 0.78645833
  0.96130153

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [39]:
a10=np.random.random(30)
print(a10)
print(a10.mean())

[0.67817064 0.40872489 0.77476988 0.28797202 0.18906978 0.48452753
 0.904159   0.52684023 0.73198536 0.3004226  0.10200398 0.2220688
 0.44854656 0.11119785 0.48110616 0.33018299 0.61305811 0.56853192
 0.32495583 0.36365582 0.63142571 0.60708067 0.40918318 0.80348472
 0.12536958 0.44327691 0.60267895 0.92349325 0.02420813 0.34094573]
0.45876989250789213


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [51]:
a11=np.diag(np.arange(1,5),k=-1)
print(a11)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [53]:
a12=np.random.random((5,5))
print(a12)
print((a12-a12.mean())/a12.std())

[[0.97211016 0.36881768 0.02850872 0.9440793  0.51724794]
 [0.56680592 0.01347659 0.36486859 0.08711846 0.3172725 ]
 [0.06457905 0.79333797 0.04859221 0.8905809  0.36499925]
 [0.62825149 0.23913874 0.06522299 0.52128354 0.11859373]
 [0.16920665 0.57417173 0.90578317 0.62342634 0.10770495]]
[[ 1.79088349 -0.13740622 -1.22512781  1.70128909  0.33701795]
 [ 0.49541898 -1.27317467 -0.1500286  -1.03779487 -0.30215889]
 [-1.10983707  1.2194781  -1.16093544  1.53029342 -0.14961097]
 [ 0.69181603 -0.551896   -1.10777887  0.34991687 -0.93719121]
 [-0.77541831  0.51896216  1.57888406  0.67639351 -0.97199474]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [56]:
a13a=[[1,2,3],[4,5,6],[7,8,9]]
a13b=[[6,7,8],[9,10,11]]

print(np.intersect1d(a13a,a13b))

[6 7 8 9]


#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [62]:
a14=np.random.random((10))
print(a14)
print(np.sort(a14))

[0.2545445  0.7611068  0.03507541 0.16569592 0.71879612 0.67662617
 0.97364717 0.09353011 0.44936768 0.60640319]
[0.03507541 0.09353011 0.16569592 0.2545445  0.44936768 0.60640319
 0.67662617 0.71879612 0.7611068  0.97364717]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [75]:
a15=np.random.random(10)
print(a15)

maxindex=np.argmax(a15)
print(maxindex)
a15[maxindex]=0
print(a15)

[0.9298372  0.67150389 0.41469047 0.49394014 0.84472844 0.85063224
 0.72918843 0.61400331 0.99366664 0.15493334]
8
[0.9298372  0.67150389 0.41469047 0.49394014 0.84472844 0.85063224
 0.72918843 0.61400331 0.         0.15493334]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [82]:
a16=np.random.random((5,5))
print(a16)


print('\n')
a16b=np.mean(a16,axis=1,keepdims=True)
print(a16b)
print('\n')


print(np.subtract(a16,a16b))

[[0.3882609  0.76435919 0.5676198  0.23716428 0.6155377 ]
 [0.36807814 0.02721862 0.92147213 0.00278452 0.92663927]
 [0.1885071  0.421889   0.11867723 0.43753259 0.21156544]
 [0.58621714 0.01497469 0.04914462 0.39853125 0.93828904]
 [0.825951   0.92968937 0.86176109 0.33830487 0.37387609]]


[[0.51458837]
 [0.44923853]
 [0.27563427]
 [0.39743135]
 [0.66591648]]


[[-0.12632747  0.24977082  0.05303143 -0.2774241   0.10094932]
 [-0.08116039 -0.42201991  0.47223359 -0.44645402  0.47740073]
 [-0.08712718  0.14625473 -0.15695704  0.16189832 -0.06406883]
 [ 0.18878579 -0.38245666 -0.34828672  0.0010999   0.54085769]
 [ 0.16003452  0.26377289  0.1958446  -0.32761162 -0.29204039]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [106]:
z=np.arange(10000)
print(z)
np.random.shuffle(z)
print(z)
n=5
z=np.argsort(z)
print(z)

print(np.argpartition(z,1))


q=np.sort(z)
print(q)
lst=[]
for i in range(1,n+1):
    lst.append(q[-i])
    
print(lst)

[   0    1    2 ... 9997 9998 9999]
[1338 7363 7980 ... 6115  862 4913]
[3065 3185  176 ... 3217 4157 4609]
[1338 7363    2 ... 9997 9998 9999]
[   0    1    2 ... 9997 9998 9999]
[9999, 9998, 9997, 9996, 9995]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [119]:
a18=np.random.randint(1,10,size=(5,3))
print(a18)
print('\n')
a18=np.where(type(a18)==int,a18,a18**2)
print(a18)

[[2 2 6]
 [1 5 8]
 [7 1 9]
 [8 3 5]
 [2 3 2]]


[[ 4  4 36]
 [ 1 25 64]
 [49  1 81]
 [64  9 25]
 [ 4  9  4]]
